# 生成镜像，需服务器有openjdk:8镜像。docker pull openjdk:8
FROM adoptopenjdk:8-jdk-hotspot

# 将jar包重命名
COPY *.jar /app.jar

# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 指定服务端口
CMD ["--server.port=9833"]

# 暴露端口
EXPOSE 9833

# 入口点：启动命令
ENTRYPOINT ["java","-jar","/app.jar"]
